# Generated by Django 3.2.6 on 2021-09-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazine', '0004_boardgame_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameLend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_start', models.DateTimeField(auto_now_add=True)),
                ('lend_end', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lended_game', to='magazine.boardgame')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='lend_app.person')),
            ],
        ),
    ]
