# Generated by Django 3.2.7 on 2021-10-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lend_app', '0003_lendinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendinformation',
            name='lend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lend_info', to='lend_app.gamelend'),
        ),
    ]
