# Generated by Django 3.2.6 on 2021-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='magazine.GameTags'),
        ),
    ]
