# Generated by Django 3.2.6 on 2021-09-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_boardgame_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='tags',
            field=models.ManyToManyField(blank=True, to='magazine.GameTags'),
        ),
    ]
