# Generated by Django 3.2.6 on 2021-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_alter_boardgame_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
